language: python
python:
    - "2.7"
    - "3.3"
before_install:
    - pip install textx
    - pip install jinja2
install:
    - pwd
    - python setup.py install
script:
    - py.test tests/functional